#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2016

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
. 'script/utils.sh'

"${PWD}/script/bootstrap"

echo "TODO: script/setup"
