#!/usr/bin/env bash
# shellcheck disable=SC1091
# shellcheck disable=SC2016

set -euo pipefail
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

echo 'script/setup'

"${PWD}/script/bootstrap"

Resources/DB/update_all.sh
